(()=>{
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const today=new Date();let calDate=new Date(today.getFullYear(),today.getMonth(),today.getDate()),currentZ=0,currentPeriod='today',currentLot=null;
const pad=n=>String(n).padStart(2,'0'),iso=d=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`;
function hash(s){let h=2166136261;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)}return Math.abs(h>>>0)}
function pseudo(seed,min=65,max=96){const x=Math.sin(seed*12.9898+78.233)*43758.5453;return Math.round(min+(x-Math.floor(x))*(max-min))}
function toast(s){const t=$('#toast');t.textContent=s;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1600)}
const daySeed=+`${today.getFullYear()}${pad(today.getMonth()+1)}${pad(today.getDate())}`;
$('#dateCn').textContent=`${today.getMonth()+1}月${today.getDate()}日`;$('#luckyHour').textContent=['卯时','辰时','巳时','午时','申时','酉时','戌时'][daySeed%7];$('#luckyWord').textContent=['静','明','和','定','善','进','舍','诚','守','新'][daySeed%10];
const stems='甲乙丙丁戊己庚辛壬癸'.split(''),branches='子丑寅卯辰巳午未申酉戌亥'.split(''),animals='鼠牛虎兔龙蛇马羊猴鸡狗猪'.split('');const mod=(n,m)=>((n%m)+m)%m;
function gzYear(y){return stems[mod(y-4,10)]+branches[mod(y-4,12)]}function gzDay(d){const ref=new Date(2000,0,7),days=Math.floor((new Date(d.getFullYear(),d.getMonth(),d.getDate())-ref)/86400000),i=6+days;return stems[mod(i,10)]+branches[mod(i,12)]}function lunar(d){try{return new Intl.DateTimeFormat('zh-CN-u-ca-chinese',{month:'long',day:'numeric'}).format(d)}catch(e){return '农历参考'}}
const terms=[[1,5,'小寒','寒气渐深'],[1,20,'大寒','岁暮严寒'],[2,4,'立春','春气始建'],[2,19,'雨水','雨润新生'],[3,6,'惊蛰','春雷动土'],[3,21,'春分','昼夜相半'],[4,5,'清明','清和景明'],[4,20,'谷雨','雨生百谷'],[5,6,'立夏','万物并秀'],[5,21,'小满','麦粒渐满'],[6,6,'芒种','有芒可种'],[6,21,'夏至','日长之极'],[7,7,'小暑','暑气渐盛'],[7,23,'大暑','炎热之极'],[8,8,'立秋','凉风将至'],[8,23,'处暑','暑气渐退'],[9,8,'白露','露凝而白'],[9,23,'秋分','昼夜再平'],[10,8,'寒露','露寒将凝'],[10,23,'霜降','霜始凝结'],[11,7,'立冬','冬气始建'],[11,22,'小雪','寒雪初候'],[12,7,'大雪','仲冬雪盛'],[12,22,'冬至','阴极阳生']];
function nearestTerm(d){const md=(d.getMonth()+1)*100+d.getDate();return terms.reduce((a,b)=>Math.abs(b[0]*100+b[1]-md)<Math.abs(a[0]*100+a[1]-md)?b:a)}
const yi=['祭祖','扫舍','读书','会友','整理账目','修剪花木','晾晒','纳福','出行','安床','洽谈','运动','整理仓储','播种','浇灌','收获','修整农具','清洁庭院'];const ji=['冲动投资','争执','熬夜','冒险远行','大额借贷','仓促决定','过量饮酒','过度劳作','忽视休息','无准备动工','情绪消费','盲目追涨','强行求成'];const farm=['晨起查看土壤墒情，浇灌宜少量多次，避免中午高温时段。','秋意渐起，可留意作物成熟度与虫害，采收后及时通风晾晒。','适合整理农具与仓储，检查防潮、防鼠与通风情况。','天气变化时先看当地预报，再安排喷施、收割或远距离运输。','庭院菜地宜去老叶、清杂草，保持根部通风但避免伤根。'];
function renderCalendar(){const d=calDate,s=hash(iso(d)),term=nearestTerm(d);$('#calDay').textContent=d.getDate();$('#calMonthYear').textContent=`${d.getFullYear()}年${d.getMonth()+1}月`;$('#calWeek').textContent='星期'+'日一二三四五六'[d.getDay()];$('#calInput').value=iso(d);$('#lunarText').textContent=lunar(d);$('#ganzhiText').textContent=`${gzYear(d.getFullYear())}年 · ${gzDay(d)}日`;$('#zodiacCn').textContent=animals[mod(d.getFullYear()-4,12)]+'年';$('#solarTerm').textContent=term[2];$('#termBig').textContent=term[2];$('#termSub').textContent=term[3];$('#yiTags').innerHTML=[...new Set([0,1,2,3,4].map(i=>yi[(s+i*7)%yi.length]))].map(x=>`<span class="tag">${x}</span>`).join('');$('#jiTags').innerHTML=[...new Set([0,1,2,3].map(i=>ji[(s+i*5)%ji.length]))].map(x=>`<span class="tag">${x}</span>`).join('');$('#farmTip').textContent=farm[s%farm.length];$('#dayKeyword').textContent=['守成','整理','播种','清心','和合','收纳','静养','推进'][s%8];$('#dayDirection').textContent=['东','东南','南','西南','西','西北','北','东北'][s%8]}
$('#prevDay').addEventListener('click',()=>{calDate.setDate(calDate.getDate()-1);renderCalendar()});$('#nextDay').addEventListener('click',()=>{calDate.setDate(calDate.getDate()+1);renderCalendar()});$('#calInput').addEventListener('change',e=>{if(e.target.value){calDate=new Date(e.target.value+'T00:00:00');renderCalendar()}});renderCalendar();
const zodiacs=[['白羊座','♈','03.21 — 04.19','火象','果断'],['金牛座','♉','04.20 — 05.20','土象','稳定'],['双子座','♊','05.21 — 06.21','风象','交流'],['巨蟹座','♋','06.22 — 07.22','水象','照顾'],['狮子座','♌','07.23 — 08.22','火象','自信'],['处女座','♍','08.23 — 09.22','土象','整理'],['天秤座','♎','09.23 — 10.23','风象','平衡'],['天蝎座','♏','10.24 — 11.22','水象','洞察'],['射手座','♐','11.23 — 12.21','火象','探索'],['摩羯座','♑','12.22 — 01.19','土象','推进'],['水瓶座','♒','01.20 — 02.18','风象','创新'],['双鱼座','♓','02.19 — 03.20','水象','感受']];
function zodiacIndex(m,d){if((m===3&&d>=21)||(m===4&&d<=19))return 0;if((m===4&&d>=20)||(m===5&&d<=20))return 1;if((m===5&&d>=21)||(m===6&&d<=21))return 2;if((m===6&&d>=22)||(m===7&&d<=22))return 3;if((m===7&&d>=23)||(m===8&&d<=22))return 4;if((m===8&&d>=23)||(m===9&&d<=22))return 5;if((m===9&&d>=23)||(m===10&&d<=23))return 6;if((m===10&&d>=24)||(m===11&&d<=22))return 7;if((m===11&&d>=23)||(m===12&&d<=21))return 8;if((m===12&&d>=22)||(m===1&&d<=19))return 9;if((m===1&&d>=20)||(m===2&&d<=18))return 10;return 11}
const periodText={today:['今天适合把犹豫压缩成一个小行动。','重视现实边界，别让情绪替你做决定。','沟通质量决定今天大部分体验。'],week:['本周主题是节奏重整。','容易出现新的信息或关系窗口。','适合完成一个长期拖延节点。'],month:['本月更像一次方向校准。','人际与合作机会增加。','适合建立新的长期习惯。']};const astro={事业:['适合推进准备成熟的计划','先抓主线，减少并行任务'],情感:['少猜，多说清真实感受','给关系留回应空间'],财运:['现金流优先于短期收益','避免冲动消费与追涨'],健康:['恢复比硬撑更重要','注意睡眠与节奏'],学业:['拆成可以完成的小段','复盘错误更有效'],人际:['真诚沟通可能打开新局面','保留高质量连接']};
$('#zodiacList').innerHTML=zodiacs.map((z,i)=>`<button class="zbtn" data-i="${i}"><strong>${z[1]}</strong><small>${z[0].replace('座','')}</small></button>`).join('');$('#zodiacList').addEventListener('click',e=>{const b=e.target.closest('.zbtn');if(b){currentZ=+b.dataset.i;renderZ()}});$('#birthday').addEventListener('change',e=>{if(!e.target.value)return;const d=new Date(e.target.value+'T00:00:00');currentZ=zodiacIndex(d.getMonth()+1,d.getDate());renderZ()});$('#periodTabs').addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;currentPeriod=b.dataset.p;$$('#periodTabs button').forEach(x=>x.classList.toggle('active',x===b));renderZ()});
function renderZ(){$$('.zbtn').forEach((b,i)=>b.classList.toggle('active',i===currentZ));const z=zodiacs[currentZ],p=currentPeriod==='today'?1:currentPeriod==='week'?7:30,s=daySeed+currentZ*97+p*131,total=pseudo(s,72,96),arr=periodText[currentPeriod],dims=['事业','情感','财运','健康','学业','人际'],scores=dims.map((_,i)=>pseudo(s+i*17,64,96));$('#zIcon').textContent=z[1];$('#zName').textContent=z[0];$('#zDate').textContent=z[2]+' · '+z[3];$('#zScore').innerHTML=`${total}<small> / 100</small>`;$('#zSummary').textContent=`${z[0]}${currentPeriod==='today'?'今日':currentPeriod==='week'?'本周':'本月'}关键词是“${z[4]}”。${arr[(s+currentZ)%arr.length]} ${arr[(s+currentZ+1)%arr.length]}`;$('#analysisCards').innerHTML=dims.slice(0,4).map((x,i)=>`<div class="mini"><b>${x}分析 · ${scores[i]}分</b><p>${astro[x][(s+i)%astro[x].length]}</p></div>`).join('');$('#zMeta').innerHTML=`<div><b>关键词</b><span>${z[4]}</span></div><div><b>幸运色</b><span>${['朱砂红','松石绿','月白','琥珀金','靛青','烟紫'][s%6]}</span></div><div><b>幸运数字</b><span>${s%9+1}</span></div><div><b>幸运方位</b><span>${['东','东南','南','西南','西','西北','北','东北'][s%8]}</span></div>`;$('#zBars').innerHTML=dims.map((x,i)=>`<div class="zbar"><b>${x}</b><div class="meter"><i style="width:${scores[i]}%"></i></div><span>${scores[i]} / 100</span></div>`).join('')}renderZ();
const stemEl=['木','木','火','火','土','土','金','金','水','水'],branchEl=['水','土','木','木','土','火','火','土','金','金','土','水'];const pillar=i=>stems[mod(i,10)]+branches[mod(i,12)];function calc(date,time){const y=date.getFullYear(),m=date.getMonth()+1,h=+(time.split(':')[0]||12),yi=y-4,mi=yi*12+m+1,ref=new Date(2000,0,7),days=Math.floor((date-ref)/86400000),di=6+days,hb=Math.floor(((h+1)%24)/2);return[pillar(yi),pillar(mi),pillar(di),pillar(di*12+hb)]}function counts(ps){const c={木:0,火:0,土:0,金:0,水:0};ps.forEach(p=>{c[stemEl[stems.indexOf(p[0])]]++;c[branchEl[branches.indexOf(p[1])]]++});return c}
$('#baziBtn').addEventListener('click',()=>{const ds=$('#birthDate').value,ts=$('#birthTime').value||'12:00',g=$('#gender').value;if(!ds){toast('请先填写出生日期');return}const ps=calc(new Date(ds+'T00:00:00'),ts),c=counts(ps),s=hash(ds+ts+g+daySeed),sc=pseudo(s,70,95),els=['木','火','土','金','水'],strong=[...els].sort((a,b)=>c[b]-c[a])[0],weak=[...els].sort((a,b)=>c[a]-c[b])[0],parts=[pseudo(s+11),pseudo(s+23),pseudo(s+37),pseudo(s+49)],r=$('#baziResult');r.classList.remove('empty');r.innerHTML=`<div class="bazi-top"><div><h3>生辰运势简析</h3><div style="color:#766b60;font-size:11px;margin-top:5px">${ds} · ${ts} · ${g}</div></div><div class="bazi-score">${sc}<small> / 100</small></div></div><div class="pillars">${['年柱','月柱','日柱','时柱'].map((x,i)=>`<div class="pillar"><small>${x}</small><strong>${ps[i]}</strong><span>${stemEl[stems.indexOf(ps[i][0])]} · ${branchEl[branches.indexOf(ps[i][1])]}</span></div>`).join('')}</div><div class="five">${els.map(e=>`<div><b>${e}</b><div class="fbar"><i style="height:${18+c[e]*30}%"></i></div><span>${c[e]} / 8</span></div>`).join('')}</div><div style="margin-top:14px;color:#a59683;font-size:13px;line-height:1.9">五行倾向以 <b style="color:#dcc094">${strong}</b> 较显，<b style="color:#dcc094">${weak}</b> 相对较弱。此结果为简化娱乐算法。</div><div class="bazi-advice">${['事业','财运','情感','身心'].map((x,i)=>`<div class="advice"><b>${x} · ${parts[i]}分</b><p>${parts[i]>82?'整体趋势较顺，适合稳步推进。':'先稳住节奏，避免急于扩大范围。'}</p></div>`).join('')}</div>`});
const lots=[{r:'上上',n:'云开见月',t:'云开月自明',p:['云开雾散见青天','一叶轻舟过远川','莫向途中频问路','花明正待有缘人'],e:'局面正从混沌走向清晰。守住已经验证有效的方向，比频繁换路更重要。',tags:['守正','渐明','贵人','宜坚持'],score:[92,86,88,84,90]},{r:'上吉',n:'春水生波',t:'一池春水起新澜',p:['春水初生绕小桥','东风一夜过林梢','若逢旧径添新意','自有轻舟趁晚潮'],e:'新的变化已经开始，旧方法稍作调整，反而能生出新机会。',tags:['新机','调整','顺势','宜行动'],score:[86,84,82,88,87]},{r:'中吉',n:'竹影清风',t:'静里自有清风来',p:['竹影摇窗月半弯','清风不语过前山','心头若少三分急','自见行舟过九湾'],e:'把节奏放稳，复杂会自行松开。',tags:['静心','稳进','忌急','渐顺'],score:[78,72,80,90,84]},{r:'上吉',n:'鸿雁传书',t:'远信终有回音时',p:['鸿雁横空过暮云','长亭有信入柴门','久候不须疑旧约','迟来消息亦逢春'],e:'等待之事有回音之象，适合清晰沟通一次，然后留出空间。',tags:['消息','沟通','有回音','勿催'],score:[82,78,89,80,84]},{r:'上上',n:'鲲鹏乘风',t:'长风正送万里舟',p:['一翼初张上碧霄','长风万里正相邀','从来远志非闲梦','今日扬帆莫待潮'],e:'若已经准备较久，现在更适合真正开始。',tags:['突破','发布','远行','宜果断'],score:[95,90,80,82,88]},{r:'平',n:'雾锁山门',t:'山在云深路未明',p:['远山隐隐入重云','行客停鞭问旧门','不是前途无去处','只缘此刻未逢辰'],e:'信息尚不足，宜多观察与验证。',tags:['观望','求证','留后路','忌冲动'],score:[61,58,62,74,70]},{r:'上上',n:'凤凰来仪',t:'百尺梧桐引凤来',p:['梧桐高处起清音','有凤来仪入上林','十载栽培非偶遇','今朝相见正同心'],e:'长期积累开始吸引更匹配的机会。',tags:['合作','被看见','贵人','成果'],score:[94,87,90,85,91]},{r:'上上',n:'日照金山',t:'朝阳一照万峰明',p:['夜尽东方第一红','千峰次第出云中','若将旧愿重新整','正可乘光上远峰'],e:'适合重新启动重要目标，并重新排序优先级。',tags:['开局','清晰','上升','宜定目标'],score:[96,91,86,88,94]}];
const topicTips={事业:['把资源集中到最能形成结果的一环。','合作先看目标是否一致。','重要决定优先依据可验证的信息。'],财运:['先守住风险边界，再考虑收益。','重要金额多一次核对。','真实投资应依据专业分析。'],情缘:['先表达事实与感受。','关系推进取决于双方真实意愿。','给回应留空间。'],学业:['把目标拆成今天能完成的一小段。','先补最薄弱的基础点。','复盘错误比机械重复更重要。'],身心:['首先照顾睡眠、饮食与恢复。','持续不适应寻求专业帮助。','安排真正能恢复的休息。'],出行:['天气、交通与安全信息优先。','行程留出缓冲。','变量多时准备备用方案。']},timing={'上上':'时机偏明朗，适合把准备已久的事真正推出去。','上吉':'节奏整体向好，适合主动但不宜急进。','中吉':'稳中渐进，先做可控动作再看反馈。','小吉':'小步前进更有利。','平':'信息尚不充分，宜多观察与验证。'};
function pickLot(){if(window.crypto&&crypto.getRandomValues){const a=new Uint32Array(1);crypto.getRandomValues(a);return a[0]%lots.length}return Math.floor(Math.random()*lots.length)}
function renderLot(lot,index){const topic=$('#topic').value,wish=$('#wish').value.trim(),z=zodiacs[currentZ];currentLot={lot,index,topic,z};$('#lotNum').textContent=String(index+1).padStart(2,'0');$('#lotRank').textContent=lot.r;$('#lotTopic').textContent=topic;$('#lotName').textContent=lot.n;$('#lotTitle').textContent=lot.t;$('#lotPoem').innerHTML=lot.p.join('<br>');$('#lotBrief').textContent=lot.e+(wish?` 你所念“${wish}”，宜先从最可执行的一步开始。`:'');$('#lotTags').innerHTML=lot.tags.map(x=>`<span class="tag">${x}</span>`).join('');const tips=topicTips[topic];$('#interpretGrid').innerHTML=`<div class="interpret"><div class="ic">意</div><h4>签意总论</h4><p>${lot.e}</p></div><div class="interpret"><div class="ic">势</div><h4>当前局势</h4><p>${tips[0]}</p></div><div class="interpret"><div class="ic">行</div><h4>行动建议</h4><p>${tips[1]} 结合${z[0]}关键词“${z[4]}”作补充提醒。</p></div><div class="interpret"><div class="ic">时</div><h4>时机提醒</h4><p>${timing[lot.r]} ${tips[2]}</p></div>`;$('#fortuneGrid').innerHTML=['事业','财运','情缘','身心','成长'].map((x,i)=>`<div class="fortune-item"><b>${x}</b><div class="bar"><i style="width:${lot.score[i]}%"></i></div><span>${lot.score[i]} / 100</span></div>`).join('');$('#interpret').classList.add('show');setTimeout(()=>$('#interpret').scrollIntoView({behavior:'smooth',block:'start'}),150)}
function draw(){const btn=$('#drawBtn'),b=$('#bowl');btn.disabled=true;btn.textContent='签 筒 · 摇 动 中';b.classList.add('shake');setTimeout(()=>{b.classList.remove('shake');const i=pickLot();renderLot(lots[i],i);btn.disabled=false;btn.textContent='静 心 · 再 摇 一 签'},1500)}
$('#drawBtn').addEventListener('click',draw);$('#againBtn').addEventListener('click',()=>{$('#draw').scrollIntoView({behavior:'smooth'});setTimeout(draw,600)});$('#copyBtn').addEventListener('click',async()=>{if(!currentLot)return;const {lot,index,topic,z}=currentLot,text=`玄签阁 · 第${String(index+1).padStart(2,'0')}签 · ${lot.r}\n${lot.t}\n${lot.p.join('\n')}\n\n解曰：${lot.e}\n所问：${topic}\n星座参考：${z[0]}\n（仅供文化娱乐参考）`;try{await navigator.clipboard.writeText(text);toast('签文已复制')}catch(e){toast('请手动复制签文')}});
})();