<?php
declare(strict_types=1);
require __DIR__.'/bootstrap.php';
admin_session_start();

$error='';$notice='';
if(isset($_POST['logout'])){session_destroy();header('Location: admin.php');exit;}

if(!admin_is_configured() && isset($_POST['setup_admin'])){
    $u=(string)($_POST['username']??'');$p=(string)($_POST['password']??'');$p2=(string)($_POST['password2']??'');
    if(!valid_username($u))$error='管理员账号需3-32位，可使用中英文、数字、下划线、点和横线。';
    elseif(!valid_password($p))$error='管理员密码至少8位，并且必须同时包含英文字母和数字。';
    elseif($p!==$p2)$error='两次输入的管理员密码不一致。';
    elseif(!save_admin_config($u,$p))$error='管理员配置写入失败，请确认 data 目录可写。';
    else{$_SESSION['xxs_admin']=1;$_SESSION['xxs_csrf']=bin2hex(random_bytes(24));header('Location: admin.php');exit;}
}

if(admin_is_configured() && !admin_ok() && isset($_POST['login_admin'])){
    $hash=admin_password_hash();
    if(hash_equals(admin_user(),trim((string)($_POST['username']??''))) && password_verify((string)($_POST['password']??''),$hash)){
        $_SESSION['xxs_admin']=1;$_SESSION['xxs_csrf']=bin2hex(random_bytes(24));header('Location: admin.php');exit;
    } else $error='管理员账号或密码错误。';
}

if(admin_ok() && isset($_POST['action'])){
    if(!csrf_ok((string)($_POST['csrf']??''))){$error='操作验证失败，请刷新页面后重试。';}
    else{
        $pdo=db();$action=(string)$_POST['action'];$id=(int)($_POST['id']??0);
        try{
            if($action==='disable_user'){$pdo->prepare('UPDATE users SET disabled=1 WHERE id=?')->execute([$id]);$notice='用户已禁用。';}
            elseif($action==='enable_user'){$pdo->prepare('UPDATE users SET disabled=0 WHERE id=?')->execute([$id]);$notice='用户已启用。';}
            elseif($action==='delete_user'){$pdo->prepare('DELETE FROM users WHERE id=?')->execute([$id]);$notice='用户及关联数据已删除。';}
            elseif($action==='clear_cache'){$uid=(int)($_POST['user_id']??0);$pdo->beginTransaction();$pdo->prepare('DELETE FROM chapter_cache WHERE user_id=?')->execute([$uid]);$pdo->prepare('DELETE FROM book_cache WHERE user_id=?')->execute([$uid]);$pdo->commit();$notice='该用户小说缓存已清空。';}
            elseif($action==='delete_draft'){$uid=(int)($_POST['user_id']??0);$draft=(string)($_POST['draft_id']??'');$pdo->prepare('DELETE FROM drafts WHERE user_id=? AND draft_id=?')->execute([$uid,$draft]);$notice='草稿已删除。';}
            elseif($action==='delete_book'){$uid=(int)($_POST['user_id']??0);$key=(string)($_POST['book_key']??'');$pdo->beginTransaction();$pdo->prepare('DELETE FROM chapter_cache WHERE user_id=? AND book_key=?')->execute([$uid,$key]);$pdo->prepare('DELETE FROM book_cache WHERE user_id=? AND book_key=?')->execute([$uid,$key]);$pdo->commit();$notice='缓存书籍已删除。';}
            elseif($action==='change_admin_password'){$p=(string)($_POST['new_password']??'');$p2=(string)($_POST['new_password2']??'');if(!valid_password($p))$error='新密码至少8位，并且必须包含英文字母和数字。';elseif($p!==$p2)$error='两次密码不一致。';elseif(change_admin_password($p))$notice='管理员密码已更新。';else $error='管理员密码更新失败。';}
        }catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();$error='操作失败：'.$e->getMessage();}
    }
}

function stat_count(string $sql): int {return (int)db()->query($sql)->fetchColumn();}
function active_nav(string $x,string $current): string{return $x===$current?' active':'';}
function short_text(string $s,int $n=80): string {$s=trim(preg_replace('/\s+/u',' ',$s));return mb_strlen($s)>$n?mb_substr($s,0,$n).'…':$s;}

if(!admin_is_configured()):
?><!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>初始化 · 小小说管理后台</title><style><?=file_get_contents(__DIR__.'/admin_style.css')?></style></head><body class="auth-body"><main class="auth-card"><div class="brand-mark">小</div><h1>创建后台管理员</h1><p class="auth-sub">首次部署只需设置一次。管理员密码至少8位，并且必须包含英文字母和数字。</p><?php if($error):?><div class="alert error"><?=h($error)?></div><?php endif?><form method="post"><label>管理员账号</label><input name="username" autocomplete="username" placeholder="例如 admin" required><label>管理员密码</label><input name="password" type="password" autocomplete="new-password" placeholder="至少8位，英文 + 数字" required><label>再次输入密码</label><input name="password2" type="password" autocomplete="new-password" required><button class="primary full" name="setup_admin" value="1">创建管理员并进入后台</button></form><div class="auth-foot">小小说 · 私人阅读与创作数据管理</div></main></body></html><?php exit;endif;

if(!admin_ok()):
?><!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>登录 · 小小说管理后台</title><style><?=file_get_contents(__DIR__.'/admin_style.css')?></style></head><body class="auth-body"><main class="auth-card"><div class="brand-mark">小</div><h1>小小说管理后台</h1><p class="auth-sub">登录后管理用户、码字草稿、私人小说缓存与服务器状态。</p><?php if($error):?><div class="alert error"><?=h($error)?></div><?php endif?><form method="post"><label>管理员账号</label><input name="username" value="<?=h(admin_user())?>" autocomplete="username" required><label>管理员密码</label><input name="password" type="password" autocomplete="current-password" required><button class="primary full" name="login_admin" value="1">登录后台</button></form><div class="auth-foot">API：<?=h(server_base_url())?>/api.php</div></main></body></html><?php exit;endif;

$view=(string)($_GET['view']??'dashboard');$allowed=['dashboard','users','drafts','cache','server','settings'];if(!in_array($view,$allowed,true))$view='dashboard';
$pdo=db();$users=stat_count('SELECT COUNT(*) FROM users');$activeUsers=stat_count('SELECT COUNT(*) FROM users WHERE disabled=0');$drafts=stat_count('SELECT COUNT(*) FROM drafts');$words=stat_count('SELECT COALESCE(SUM(words),0) FROM drafts');$books=stat_count('SELECT COUNT(*) FROM book_cache');$chapters=stat_count('SELECT COUNT(*) FROM chapter_cache');
$dbFile=app_data_dir().'/xiaoxiaoshuo.sqlite';$dbSize=is_file($dbFile)?filesize($dbFile):0;$phpVersion=PHP_VERSION;$sqliteOk=in_array('sqlite',PDO::getAvailableDrivers(),true);
?><!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>小小说管理后台</title><style><?=file_get_contents(__DIR__.'/admin_style.css')?></style></head><body><div class="layout">
<aside class="sidebar"><div class="brand"><div class="brand-mark small">小</div><div><strong>小小说</strong><span>管理后台</span></div></div><nav><a class="<?=active_nav('dashboard',$view)?>" href="?view=dashboard"><b>⌂</b>仪表盘</a><a class="<?=active_nav('users',$view)?>" href="?view=users"><b>◎</b>用户管理</a><a class="<?=active_nav('drafts',$view)?>" href="?view=drafts"><b>✎</b>码字草稿</a><a class="<?=active_nav('cache',$view)?>" href="?view=cache"><b>▣</b>小说缓存</a><a class="<?=active_nav('server',$view)?>" href="?view=server"><b>◫</b>服务器状态</a><a class="<?=active_nav('settings',$view)?>" href="?view=settings"><b>⚙</b>后台设置</a></nav><div class="sidebar-foot"><span>API v1</span><small><?=h(date('Y-m-d'))?></small></div></aside>
<main class="main"><header class="topbar"><div><h1><?=['dashboard'=>'仪表盘','users'=>'用户管理','drafts'=>'码字草稿','cache'=>'小说缓存','server'=>'服务器状态','settings'=>'后台设置'][$view]?></h1><p><?=['dashboard'=>'查看小小说服务整体运行情况','users'=>'管理注册用户和账号状态','drafts'=>'查看与管理用户私人码字草稿','cache'=>'查看服务器上的私人离线小说缓存','server'=>'检查 PHP、SQLite、API 与存储状态','settings'=>'管理管理员密码与接口信息'][$view]?></p></div><div class="top-actions"><span class="admin-pill"><?=h(admin_user())?></span><form method="post"><button class="ghost" name="logout" value="1">退出</button></form></div></header>
<?php if($error):?><div class="alert error"><?=h($error)?></div><?php endif?><?php if($notice):?><div class="alert success"><?=h($notice)?></div><?php endif?>

<?php if($view==='dashboard'):?>
<section class="stats"><div class="stat-card"><span>注册用户</span><strong><?=$users?></strong><small><?=$activeUsers?> 个正常账号</small></div><div class="stat-card"><span>码字草稿</span><strong><?=$drafts?></strong><small><?=number_format($words)?> 字</small></div><div class="stat-card"><span>私人缓存书籍</span><strong><?=$books?></strong><small>按账号隔离存储</small></div><div class="stat-card"><span>缓存章节</span><strong><?=$chapters?></strong><small><?=bytes_human((int)$dbSize)?> 数据库</small></div></section>
<div class="two-col"><section class="panel"><div class="panel-head"><div><h2>最近注册用户</h2><p>最近创建的 8 个账号</p></div><a href="?view=users">查看全部</a></div><div class="table-wrap"><table><thead><tr><th>用户</th><th>注册时间</th><th>最近登录</th><th>状态</th></tr></thead><tbody><?php $rs=$pdo->query('SELECT id,username,created_at,last_login,disabled FROM users ORDER BY id DESC LIMIT 8')->fetchAll();foreach($rs as $r):?><tr><td><strong><?=h($r['username'])?></strong><small>#<?=$r['id']?></small></td><td><?=date('Y-m-d H:i',(int)$r['created_at'])?></td><td><?=$r['last_login']?date('m-d H:i',(int)$r['last_login']):'未登录'?></td><td><span class="badge <?=$r['disabled']?'bad':'ok'?>"><?=$r['disabled']?'已禁用':'正常'?></span></td></tr><?php endforeach;if(!$rs):?><tr><td colspan="4" class="empty">暂无注册用户</td></tr><?php endif?></tbody></table></div></section>
<section class="panel"><div class="panel-head"><div><h2>服务状态</h2><p>当前空间基础运行信息</p></div><span class="badge ok">在线</span></div><div class="health"><div><span>PHP</span><b><?=h($phpVersion)?></b></div><div><span>PDO SQLite</span><b class="<?=$sqliteOk?'good':'warn'?>"><?=$sqliteOk?'可用':'不可用'?></b></div><div><span>数据库</span><b><?=bytes_human((int)$dbSize)?></b></div><div><span>API 地址</span><b class="mono small-text"><?=h(server_base_url())?>/api.php</b></div></div></section></div>

<?php elseif($view==='users'):?>
<section class="panel"><div class="panel-head"><div><h2>全部用户</h2><p>共 <?=$users?> 个账号</p></div></div><div class="table-wrap"><table><thead><tr><th>ID</th><th>用户名</th><th>注册 / 登录</th><th>草稿</th><th>小说缓存</th><th>状态</th><th>操作</th></tr></thead><tbody><?php $rows=$pdo->query('SELECT u.id,u.username,u.created_at,u.last_login,u.disabled,(SELECT COUNT(*) FROM drafts d WHERE d.user_id=u.id) drafts,(SELECT COUNT(*) FROM book_cache b WHERE b.user_id=u.id) books,(SELECT COUNT(*) FROM chapter_cache c WHERE c.user_id=u.id) chapters FROM users u ORDER BY u.id DESC')->fetchAll();foreach($rows as $r):?><tr><td>#<?=$r['id']?></td><td><strong><?=h($r['username'])?></strong></td><td><?=date('Y-m-d',(int)$r['created_at'])?><small><?=$r['last_login']?date('Y-m-d H:i',(int)$r['last_login']):'未登录'?></small></td><td><?=$r['drafts']?></td><td><?=$r['books']?> 本<small><?=$r['chapters']?> 章</small></td><td><span class="badge <?=$r['disabled']?'bad':'ok'?>"><?=$r['disabled']?'禁用':'正常'?></span></td><td class="actions"><form method="post"><input type="hidden" name="csrf" value="<?=h(csrf_token())?>"><input type="hidden" name="id" value="<?=$r['id']?>"><button class="mini" name="action" value="<?=$r['disabled']?'enable_user':'disable_user'?>"><?=$r['disabled']?'启用':'禁用'?></button></form><form method="post" onsubmit="return confirm('清空该用户全部服务器小说缓存？')"><input type="hidden" name="csrf" value="<?=h(csrf_token())?>"><input type="hidden" name="user_id" value="<?=$r['id']?>"><button class="mini" name="action" value="clear_cache">清缓存</button></form><form method="post" onsubmit="return confirm('确定删除该用户和全部数据？此操作不可恢复。')"><input type="hidden" name="csrf" value="<?=h(csrf_token())?>"><input type="hidden" name="id" value="<?=$r['id']?>"><button class="mini danger" name="action" value="delete_user">删除</button></form></td></tr><?php endforeach;if(!$rows):?><tr><td colspan="7" class="empty">暂无用户</td></tr><?php endif?></tbody></table></div></section>

<?php elseif($view==='drafts'):?>
<section class="panel"><div class="panel-head"><div><h2>用户草稿</h2><p>服务器只保存用户主动同步的私人草稿</p></div><span class="badge neutral"><?=number_format($words)?> 字</span></div><div class="table-wrap"><table><thead><tr><th>作品</th><th>用户</th><th>字数</th><th>最近同步</th><th>正文预览</th><th>操作</th></tr></thead><tbody><?php $rows=$pdo->query('SELECT d.*,u.username FROM drafts d JOIN users u ON u.id=d.user_id ORDER BY d.updated_at DESC')->fetchAll();foreach($rows as $r):?><tr><td><strong><?=h($r['title'])?></strong><small><?=h($r['draft_id'])?></small></td><td><?=h($r['username'])?></td><td><?=number_format((int)$r['words'])?></td><td><?=date('Y-m-d H:i',(int)$r['updated_at'])?></td><td class="preview"><?=h(short_text($r['content'],90))?></td><td><form method="post" onsubmit="return confirm('删除这份服务器草稿？')"><input type="hidden" name="csrf" value="<?=h(csrf_token())?>"><input type="hidden" name="user_id" value="<?=$r['user_id']?>"><input type="hidden" name="draft_id" value="<?=h($r['draft_id'])?>"><button class="mini danger" name="action" value="delete_draft">删除</button></form></td></tr><?php endforeach;if(!$rows):?><tr><td colspan="6" class="empty">暂无服务器草稿</td></tr><?php endif?></tbody></table></div></section>

<?php elseif($view==='cache'):?>
<section class="panel"><div class="panel-head"><div><h2>私人小说缓存</h2><p>每个账号独立保存，不公开、不共享</p></div><span class="badge neutral"><?=$books?> 本 / <?=$chapters?> 章</span></div><div class="table-wrap"><table><thead><tr><th>书籍</th><th>用户</th><th>书源</th><th>目录</th><th>已缓存章节</th><th>更新时间</th><th>操作</th></tr></thead><tbody><?php $rows=$pdo->query('SELECT b.*,u.username,(SELECT COUNT(*) FROM chapter_cache c WHERE c.user_id=b.user_id AND c.book_key=b.book_key) cached FROM book_cache b JOIN users u ON u.id=b.user_id ORDER BY b.updated_at DESC')->fetchAll();foreach($rows as $r):$catalog=json_decode($r['chapters_json'],true);$total=is_array($catalog)?count($catalog):0;?><tr><td><strong><?=h($r['title'])?></strong><small><?=h($r['author'])?></small></td><td><?=h($r['username'])?></td><td><?=h($r['source_name']?:'未知书源')?></td><td><?=$total?> 章</td><td><strong><?=$r['cached']?></strong> 章</td><td><?=date('Y-m-d H:i',(int)$r['updated_at'])?></td><td><form method="post" onsubmit="return confirm('删除此用户这本书的全部服务器缓存？')"><input type="hidden" name="csrf" value="<?=h(csrf_token())?>"><input type="hidden" name="user_id" value="<?=$r['user_id']?>"><input type="hidden" name="book_key" value="<?=h($r['book_key'])?>"><button class="mini danger" name="action" value="delete_book">删除缓存</button></form></td></tr><?php endforeach;if(!$rows):?><tr><td colspan="7" class="empty">暂无服务器小说缓存</td></tr><?php endif?></tbody></table></div></section>

<?php elseif($view==='server'):?>
<div class="two-col"><section class="panel"><div class="panel-head"><div><h2>运行环境</h2><p>免费 PHP 空间兼容检查</p></div></div><div class="health large"><div><span>PHP 版本</span><b><?=h($phpVersion)?></b></div><div><span>PDO SQLite</span><b class="<?=$sqliteOk?'good':'warn'?>"><?=$sqliteOk?'正常':'未启用'?></b></div><div><span>数据目录</span><b class="<?=is_writable(app_data_dir())?'good':'warn'?>"><?=is_writable(app_data_dir())?'可写':'不可写'?></b></div><div><span>数据库大小</span><b><?=bytes_human((int)$dbSize)?></b></div><div><span>内存限制</span><b><?=h((string)ini_get('memory_limit'))?></b></div><div><span>上传限制</span><b><?=h((string)ini_get('upload_max_filesize'))?></b></div></div></section><section class="panel"><div class="panel-head"><div><h2>API 信息</h2><p>填写到小小说 APP 的服务器地址</p></div></div><div class="api-box"><label>服务器基础地址</label><div class="copy-row"><code><?=h(server_base_url())?></code></div><label>API 地址</label><div class="copy-row"><code><?=h(server_base_url())?>/api.php</code></div><label>后台地址</label><div class="copy-row"><code><?=h(server_base_url())?>/admin.php</code></div></div></section></div><section class="panel"><div class="panel-head"><div><h2>数据统计</h2><p>当前 SQLite 数据库存储情况</p></div></div><div class="stats compact"><div class="stat-card"><span>用户</span><strong><?=$users?></strong></div><div class="stat-card"><span>草稿</span><strong><?=$drafts?></strong></div><div class="stat-card"><span>书籍</span><strong><?=$books?></strong></div><div class="stat-card"><span>章节</span><strong><?=$chapters?></strong></div></div></section>

<?php elseif($view==='settings'):?>
<div class="two-col"><section class="panel"><div class="panel-head"><div><h2>管理员账号</h2><p>当前管理员：<?=h(admin_user())?></p></div></div><form method="post" class="form"><input type="hidden" name="csrf" value="<?=h(csrf_token())?>"><label>新管理员密码</label><input type="password" name="new_password" placeholder="至少8位，英文 + 数字" required><label>再次输入新密码</label><input type="password" name="new_password2" required><button class="primary" name="action" value="change_admin_password">修改管理员密码</button></form></section><section class="panel"><div class="panel-head"><div><h2>部署信息</h2><p>普通 PHP 免费空间即可运行</p></div></div><div class="health large"><div><span>后台版本</span><b>2.0.0</b></div><div><span>数据库</span><b>SQLite</b></div><div><span>账号密码</span><b>password_hash</b></div><div><span>API Token</span><b>SHA-256</b></div><div><span>数据隔离</span><b>按用户隔离</b></div></div></section></div>
<?php endif?>
<footer>小小说管理后台 2.0.0 · 私人阅读与创作数据服务</footer></main></div></body></html>
