plugins {
    id 'com.android.application'
}

android {
    namespace 'com.xiaoxiaoshuo.reader'
    compileSdk 35

    defaultConfig {
        applicationId 'com.xiaoxiaoshuo.reader'
        minSdk 23
        targetSdk 29
        versionCode 10007
        versionName '10.0.7'
    }

    lint {
        disable 'ExpiredTargetSdkVersion'
        abortOnError false
        checkReleaseBuilds false
    }

    buildTypes {
        release {
            minifyEnabled false
            shrinkResources false
        }
    }
}
