package com.xiaoxiaoshuo.reader;
import android.app.*;import android.os.*;import android.content.*;import android.graphics.*;import android.graphics.drawable.GradientDrawable;import android.view.*;import android.widget.*;import org.json.JSONObject;import java.util.*;

public class BookDetailActivity extends Activity{
 private final int green=Color.rgb(49,88,71);private LinearLayout catalogBox;private TextView status,titleView,authorView,introView,sourceView;private ImageView coverView;private LegacyDexBridge.BookResult book=new LegacyDexBridge.BookResult();private ArrayList<LegacyDexBridge.Chapter> chapters=new ArrayList<>();private int shown=0;private String catalogKey="";private volatile int catalogToken=0;
 @Override public void onCreate(Bundle b){super.onCreate(b);readIntent();build();resolveAndCatalog();}
 private void readIntent(){Intent i=getIntent();book.title=n(i,"title");book.author=n(i,"author");book.intro=n(i,"intro");book.coverUrl=n(i,"cover");book.bookUrl=n(i,"book_url");book.sourceName=n(i,"source_name");book.sourceUrl=n(i,"source_url");book.sourceJson=n(i,"source_json");}private String n(Intent i,String k){String s=i.getStringExtra(k);return s==null?"":s;}
 private void build(){
  LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(Color.rgb(247,244,238));
  FrameLayout top=new FrameLayout(this);top.setPadding(dp(10),dp(7),dp(10),dp(6));TextView back=tx("‹",32,green,true);back.setGravity(Gravity.CENTER);back.setOnClickListener(v->finish());FrameLayout.LayoutParams bp=new FrameLayout.LayoutParams(dp(50),dp(50),Gravity.LEFT|Gravity.CENTER_VERTICAL);top.addView(back,bp);TextView topTitle=tx("书籍详情",18,Color.rgb(44,53,48),true);topTitle.setGravity(Gravity.CENTER);FrameLayout.LayoutParams tp=new FrameLayout.LayoutParams(dp(180),dp(50),Gravity.CENTER);top.addView(topTitle,tp);root.addView(top,new LinearLayout.LayoutParams(-1,dp(64)));
  ScrollView sv=new ScrollView(this);LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(dp(20),dp(12),dp(20),dp(36));
  LinearLayout hero=card();hero.setOrientation(LinearLayout.HORIZONTAL);coverView=new ImageView(this);coverView.setImageDrawable(new LiteraryCoverDrawable(book.title));hero.addView(coverView,new LinearLayout.LayoutParams(dp(112),dp(158)));LinearLayout info=new LinearLayout(this);info.setOrientation(LinearLayout.VERTICAL);info.setPadding(dp(16),dp(4),0,0);titleView=tx(book.title.length()>0?book.title:"未命名书籍",23,Color.rgb(39,49,44),true);info.addView(titleView);authorView=tx(book.author.length()>0?book.author:"作者待获取",14,Color.rgb(116,108,97),false);authorView.setPadding(0,dp(7),0,dp(9));info.addView(authorView);sourceView=tx(book.sourceName.length()>0?"来源 · "+book.sourceName:"正在匹配优质书源",12,green,true);info.addView(sourceView);hero.addView(info,new LinearLayout.LayoutParams(0,dp(158),1));box.addView(hero,mp(0,0,0,14));CoverLoader.load(coverView,book.coverUrl,book.bookUrl.length()>0?book.bookUrl:book.sourceUrl,book.sourceJson,book.title);
  introView=tx(book.intro.length()>0?book.intro:"正在获取完整简介…",14,Color.rgb(77,75,70),false);introView.setLineSpacing(dp(4),1f);LinearLayout intro=card();intro.addView(introView);box.addView(intro,mp(0,0,0,14));
  LinearLayout actions=new LinearLayout(this);actions.setGravity(Gravity.CENTER_VERTICAL);TextView shelf=actionButton("＋  加入书架",false);shelf.setOnClickListener(v->addShelf());TextView read=actionButton("▶  开始阅读",true);read.setOnClickListener(v->{if(chapters.isEmpty())Toast.makeText(this,"目录还没有加载完成",Toast.LENGTH_SHORT).show();else openChapter(savedProgress());});actions.addView(shelf,new LinearLayout.LayoutParams(0,dp(54),1));LinearLayout.LayoutParams rp=new LinearLayout.LayoutParams(0,dp(54),1);rp.leftMargin=dp(12);actions.addView(read,rp);box.addView(actions,mp(0,0,0,22));
  LinearLayout titleRow=new LinearLayout(this);titleRow.setGravity(Gravity.CENTER_VERTICAL);titleRow.addView(tx("章节目录",20,Color.rgb(43,58,50),true),new LinearLayout.LayoutParams(0,-2,1));status=tx("正在查找目录…",12,Color.rgb(130,122,110),false);status.setGravity(Gravity.CENTER_VERTICAL);titleRow.addView(status);box.addView(titleRow,mp(0,0,0,10));catalogBox=new LinearLayout(this);catalogBox.setOrientation(LinearLayout.VERTICAL);box.addView(catalogBox);sv.addView(box);root.addView(sv,new LinearLayout.LayoutParams(-1,0,1));setContentView(root);getWindow().setStatusBarColor(Color.rgb(247,244,238));getWindow().getDecorView().setSystemUiVisibility(View.SYSTEM_UI_FLAG_LIGHT_STATUS_BAR);
 }

 private void resolveAndCatalog(){final int token=++catalogToken;new Thread(()->{
  BookSourceResolver.Resolved initial=null;
  try{if(book.sourceJson.length()>0)initial=BookSourceResolver.inspect(this,book);if(initial==null){BookSourceResolver.Resolved found=BookSourceResolver.bestForTitle(this,book.title,book.author,book,24);initial=found;}}
  catch(Throwable ignored){}
  final BookSourceResolver.Resolved first=initial;
  runOnUiThread(()->{if(token!=catalogToken)return;if(first==null){status.setText("暂未获取到目录，正在继续寻找更完整书源…");}else applyResolved(first,false);});
  BookSourceResolver.Resolved best=null;try{best=BookSourceResolver.bestForTitle(this,book.title,book.author,first==null?book:first.book,80);}catch(Throwable ignored){}
  final BookSourceResolver.Resolved finalBest=best;runOnUiThread(()->{if(token!=catalogToken)return;if(finalBest==null){if(chapters.isEmpty())showNoCatalog();return;}int old=chapters.size();if(old==0||finalBest.chapterCount()>old){applyResolved(finalBest,old>0);if(old>0)Toast.makeText(this,"已自动切换到目录更全的书源："+finalBest.chapterCount()+"章",Toast.LENGTH_LONG).show();}else status.setText("共 "+chapters.size()+" 章 · 当前已是较完整目录 · 全本离线中");});
 }).start();}

 private void applyResolved(BookSourceResolver.Resolved r,boolean switched){if(r==null||r.book==null||r.chapters.isEmpty())return;book=r.book;chapters=new ArrayList<>(r.chapters);catalogKey=CatalogStore.save(this,book.title,book.sourceJson,chapters);OfflineBookCache.saveBook(this,book,chapters);titleView.setText(book.title);authorView.setText(book.author.length()>0?book.author:"作者未知");sourceView.setText((switched?"已切换 · ":"来源 · ")+(book.sourceName.length()>0?book.sourceName:"优质书源"));introView.setText(book.intro.length()>0?AiTypesetter.compactIntro(book.intro):"暂无简介");CoverLoader.load(coverView,book.coverUrl,book.bookUrl.length()>0?book.bookUrl:book.sourceUrl,book.sourceJson,book.title);status.setText("共 "+chapters.size()+" 章 · 正在比较更完整目录");catalogBox.removeAllViews();shown=0;showMore();}
 private void showNoCatalog(){status.setText("优选书源均暂未获取到目录");catalogBox.removeAllViews();TextView tip=tx("应用会继续更新书源；再次进入时会优先寻找章节更多的版本。",14,Color.rgb(105,98,88),false);tip.setPadding(dp(14),dp(18),dp(14),dp(18));catalogBox.addView(tip);}
 private void showMore(){int end=Math.min(chapters.size(),shown+80);for(int i=shown;i<end;i++){final int idx=i;LegacyDexBridge.Chapter ch=chapters.get(i);TextView row=tx((i+1)+"  "+ch.name,15,Color.rgb(61,66,62),false);row.setPadding(dp(12),dp(14),dp(12),dp(14));row.setBackgroundColor(i%2==0?Color.WHITE:Color.rgb(251,249,244));row.setOnClickListener(v->openChapter(idx));catalogBox.addView(row,new LinearLayout.LayoutParams(-1,-2));}shown=end;if(shown<chapters.size()){TextView more=actionButton("加载更多章节（剩余 "+(chapters.size()-shown)+"）",false);more.setOnClickListener(v->{catalogBox.removeView(v);showMore();});catalogBox.addView(more,new LinearLayout.LayoutParams(-1,dp(52)));}}
 private int savedProgress(){return Math.max(0,Math.min(getSharedPreferences("reading_progress",MODE_PRIVATE).getInt("idx_"+Integer.toHexString(book.title.hashCode()),0),Math.max(0,chapters.size()-1)));}
 private void openChapter(int idx){if(idx<0||idx>=chapters.size())return;Intent i=new Intent(this,ReaderActivity.class);i.putExtra("title",book.title);i.putExtra("catalog_key",catalogKey);i.putExtra("chapter_index",idx);i.putExtra("source_json",book.sourceJson);startActivity(i);}
 private void addShelf(){try{String key="book_"+Integer.toHexString(book.title.hashCode());getSharedPreferences("native_shelf",MODE_PRIVATE).edit().putString(key,new JSONObject().put("title",book.title).put("author",book.author).put("intro",book.intro).put("cover",book.coverUrl).put("book_url",book.bookUrl).put("source_name",book.sourceName).put("source_url",book.sourceUrl).put("source_json",book.sourceJson).toString()).apply();LinkedHashSet<String> set=new LinkedHashSet<>(getSharedPreferences("native_shelf",MODE_PRIVATE).getStringSet("keys",Collections.emptySet()));set.add(key);getSharedPreferences("native_shelf",MODE_PRIVATE).edit().putStringSet("keys",set).apply();OfflineBookCache.saveBook(this,book,chapters);Toast.makeText(this,"已加入书架 · 正在自动离线全本",Toast.LENGTH_SHORT).show();}catch(Throwable e){Toast.makeText(this,"加入书架失败",Toast.LENGTH_SHORT).show();}}
 private TextView actionButton(String s,boolean primary){TextView v=tx(s,15,primary?Color.WHITE:green,true);v.setGravity(Gravity.CENTER);GradientDrawable d=new GradientDrawable();d.setCornerRadius(dp(16));if(primary)d.setColor(green);else{d.setColor(Color.rgb(239,246,241));d.setStroke(dp(1.3f),Color.rgb(76,116,94));}v.setBackground(d);return v;}
 private LinearLayout card(){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(16),dp(16),dp(16),dp(16));GradientDrawable g=new GradientDrawable();g.setColor(Color.WHITE);g.setCornerRadius(dp(18));c.setBackground(g);return c;}private TextView tx(String s,int size,int color,boolean bold){TextView v=new TextView(this);v.setText(s);v.setTextSize(size);v.setTextColor(color);v.setTypeface(Typeface.create("sans",bold?Typeface.BOLD:Typeface.NORMAL));return v;}private LinearLayout.LayoutParams mp(int l,int t,int r,int b){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(dp(l),dp(t),dp(r),dp(b));return p;}private int dp(float n){return(int)(n*getResources().getDisplayMetrics().density+.5f);}
}
