package com.xiaoxiaoshuo.reader;
import android.content.Context;import org.json.*;import java.io.*;import java.security.MessageDigest;import java.util.*;
public final class CatalogStore{
 private CatalogStore(){}
 public static String save(Context c,String title,String sourceJson,List<LegacyDexBridge.Chapter> chapters){try{String key=hash(title+"|"+sourceJson);JSONArray a=new JSONArray();for(LegacyDexBridge.Chapter ch:chapters){JSONObject o=new JSONObject();o.put("name",ch.name);o.put("url",ch.url);a.put(o);}JSONObject root=new JSONObject();root.put("sourceJson",sourceJson);root.put("title",title);root.put("chapters",a);File f=new File(c.getFilesDir(),"catalog_"+key+".json");FileOutputStream out=new FileOutputStream(f);out.write(root.toString().getBytes("UTF-8"));out.close();return key;}catch(Throwable e){return "";}}
 public static Data load(Context c,String key){Data d=new Data();try{File f=new File(c.getFilesDir(),"catalog_"+key+".json");if(!f.isFile())return d;byte[] b=new byte[(int)Math.min(f.length(),4*1024*1024)];FileInputStream in=new FileInputStream(f);int n=in.read(b);in.close();JSONObject root=new JSONObject(new String(b,0,Math.max(0,n),"UTF-8"));d.sourceJson=root.optString("sourceJson","");d.title=root.optString("title","");JSONArray a=root.optJSONArray("chapters");if(a!=null)for(int i=0;i<a.length();i++){JSONObject o=a.optJSONObject(i);if(o!=null)d.chapters.add(new LegacyDexBridge.Chapter(o.optString("name"),o.optString("url")));}}catch(Throwable ignored){}return d;}
 public static void deleteFor(Context c,String title,String sourceJson){try{File f=new File(c.getFilesDir(),"catalog_"+hash((title==null?"":title)+"|"+(sourceJson==null?"":sourceJson))+".json");if(f.exists())f.delete();}catch(Throwable ignored){}}
 public static final class Data{public String sourceJson="",title="";public final ArrayList<LegacyDexBridge.Chapter> chapters=new ArrayList<>();}
 private static String hash(String s)throws Exception{MessageDigest m=MessageDigest.getInstance("SHA-1");byte[] b=m.digest(s.getBytes("UTF-8"));StringBuilder x=new StringBuilder();for(byte q:b)x.append(String.format(Locale.US,"%02x",q));return x.toString();}
}
