package com.xiaoxiaoshuo.reader;

import android.app.*;import android.os.*;import android.content.*;import android.graphics.*;import android.graphics.drawable.GradientDrawable;import android.view.*;import android.widget.*;import java.util.*;

public class HotCategoryActivity extends Activity{
 private final int green=Color.rgb(49,88,71);private LinearLayout categoryRow,listBox;private TextView title,status,pageText;private String current="男频热门";private ArrayList<HotCategoryStore.Item> items=new ArrayList<>();private int page=0;private final int pageSize=10;
 @Override public void onCreate(Bundle b){super.onCreate(b);build();loadCategory(current);}
 private void build(){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(Color.rgb(247,244,238));
  FrameLayout top=new FrameLayout(this);top.setPadding(dp(10),dp(7),dp(10),dp(6));TextView back=tx("‹",32,green,true);back.setGravity(Gravity.CENTER);back.setOnClickListener(v->finish());top.addView(back,new FrameLayout.LayoutParams(dp(50),dp(50),Gravity.LEFT|Gravity.CENTER_VERTICAL));title=tx("热门小说",19,Color.rgb(43,54,48),true);title.setGravity(Gravity.CENTER);top.addView(title,new FrameLayout.LayoutParams(dp(200),dp(50),Gravity.CENTER));root.addView(top,new LinearLayout.LayoutParams(-1,dp(64)));
  TextView sub=tx("分类推荐每天更新一次，同一天优先读取缓存，不会反复变化",12,Color.rgb(126,118,107),false);sub.setPadding(dp(18),0,dp(18),dp(8));root.addView(sub);
  HorizontalScrollView hs=new HorizontalScrollView(this);hs.setHorizontalScrollBarEnabled(false);categoryRow=new LinearLayout(this);categoryRow.setOrientation(LinearLayout.HORIZONTAL);categoryRow.setPadding(dp(14),dp(5),dp(8),dp(9));for(String c:HotCategoryStore.CATEGORIES)categoryRow.addView(categoryChip(c));hs.addView(categoryRow);root.addView(hs,new LinearLayout.LayoutParams(-1,dp(54)));
  status=tx("",12,Color.rgb(122,116,106),false);status.setPadding(dp(18),dp(4),dp(18),dp(10));root.addView(status);
  ScrollView sv=new ScrollView(this);listBox=new LinearLayout(this);listBox.setOrientation(LinearLayout.VERTICAL);listBox.setPadding(dp(16),0,dp(16),dp(12));sv.addView(listBox);root.addView(sv,new LinearLayout.LayoutParams(-1,0,1));
  LinearLayout pager=new LinearLayout(this);pager.setGravity(Gravity.CENTER);pager.setPadding(dp(16),dp(6),dp(16),dp(8));TextView prev=pageButton("‹ 上一页");prev.setOnClickListener(v->{if(page>0){page--;render();}});pageText=tx("1 / 1",13,Color.rgb(113,106,96),false);pageText.setGravity(Gravity.CENTER);TextView next=pageButton("下一页 ›");next.setOnClickListener(v->{int pc=Math.max(1,(items.size()+pageSize-1)/pageSize);if(page+1<pc){page++;render();}});pager.addView(prev,new LinearLayout.LayoutParams(0,dp(46),1));pager.addView(pageText,new LinearLayout.LayoutParams(0,dp(46),1));pager.addView(next,new LinearLayout.LayoutParams(0,dp(46),1));root.addView(pager,new LinearLayout.LayoutParams(-1,dp(62)));
  setContentView(root);getWindow().setStatusBarColor(Color.rgb(247,244,238));getWindow().getDecorView().setSystemUiVisibility(View.SYSTEM_UI_FLAG_LIGHT_STATUS_BAR);
 }
 private TextView categoryChip(String c){TextView v=tx(c,13,green,c.equals(current));v.setGravity(Gravity.CENTER);v.setPadding(dp(13),dp(6),dp(13),dp(6));GradientDrawable d=new GradientDrawable();d.setColor(c.equals(current)?Color.rgb(225,239,229):Color.WHITE);d.setCornerRadius(dp(17));d.setStroke(dp(1),Color.rgb(221,229,223));v.setBackground(d);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-2,dp(36));p.setMargins(0,0,dp(8),0);v.setLayoutParams(p);v.setOnClickListener(x->loadCategory(c));return v;}
 private void refreshChips(){categoryRow.removeAllViews();for(String c:HotCategoryStore.CATEGORIES)categoryRow.addView(categoryChip(c));}
 private void loadCategory(String c){current=c;page=0;refreshChips();title.setText(c);status.setText("正在读取 "+c+" 每日缓存…");listBox.removeAllViews();TextView loading=tx("正在整理热门小说…",14,Color.rgb(108,101,92),false);loading.setPadding(dp(8),dp(24),dp(8),dp(24));listBox.addView(loading);HotCategoryStore.load(this,c,(list,fromCache)->runOnUiThread(()->{if(!current.equals(c))return;items=new ArrayList<>(list);page=0;status.setText(c+" · "+items.size()+" 本 · "+(fromCache?"今日缓存":"今日已更新"));render();}));}
 private void render(){listBox.removeAllViews();if(items.isEmpty()){TextView e=tx("当前分类暂时没有通过目录完整性验证的小说，稍后会自动更新。",14,Color.rgb(110,103,94),false);e.setPadding(dp(8),dp(26),dp(8),dp(26));listBox.addView(e);pageText.setText("1 / 1");return;}int pc=Math.max(1,(items.size()+pageSize-1)/pageSize);page=Math.max(0,Math.min(page,pc-1));int start=page*pageSize,end=Math.min(items.size(),start+pageSize);for(int i=start;i<end;i++)listBox.addView(bookCard(items.get(i)),mp(0,0,0,11));pageText.setText((page+1)+" / "+pc);}
 private View bookCard(HotCategoryStore.Item it){LegacyDexBridge.BookResult b=it.book;LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.HORIZONTAL);c.setPadding(dp(12),dp(12),dp(12),dp(12));GradientDrawable g=new GradientDrawable();g.setColor(Color.WHITE);g.setCornerRadius(dp(18));c.setBackground(g);ImageView cover=new ImageView(this);cover.setImageDrawable(new LiteraryCoverDrawable(b.title));c.addView(cover,new LinearLayout.LayoutParams(dp(84),dp(118)));CoverLoader.load(cover,b.coverUrl,b.bookUrl.length()>0?b.bookUrl:b.sourceUrl,b.sourceJson,b.title);LinearLayout info=new LinearLayout(this);info.setOrientation(LinearLayout.VERTICAL);info.setPadding(dp(14),0,0,0);LinearLayout row=new LinearLayout(this);row.setGravity(Gravity.CENTER_VERTICAL);row.addView(tx(b.title,18,Color.rgb(39,49,44),true),new LinearLayout.LayoutParams(0,-2,1));TextView n=tx(it.chapters+"章",12,Color.WHITE,true);n.setGravity(Gravity.CENTER);n.setPadding(dp(8),dp(3),dp(8),dp(3));GradientDrawable badge=new GradientDrawable();badge.setColor(green);badge.setCornerRadius(dp(12));n.setBackground(badge);row.addView(n);info.addView(row);TextView a=tx(b.author.length()>0?b.author:"作者未知",12,Color.rgb(127,119,108),false);a.setPadding(0,dp(4),0,dp(7));info.addView(a);TextView intro=tx(b.intro.length()>0?AiTypesetter.compactIntro(b.intro):"已验证目录完整性，点击阅读",13,Color.rgb(82,80,75),false);intro.setMaxLines(3);info.addView(intro);TextView go=tx("详情 · 阅读 ›",13,green,true);go.setGravity(Gravity.RIGHT|Gravity.BOTTOM);info.addView(go,new LinearLayout.LayoutParams(-1,0,1));c.addView(info,new LinearLayout.LayoutParams(0,dp(118),1));c.setOnClickListener(v->{Intent x=new Intent(this,BookDetailActivity.class);x.putExtra("title",b.title);x.putExtra("author",b.author);x.putExtra("intro",b.intro);x.putExtra("cover",b.coverUrl);x.putExtra("book_url",b.bookUrl);x.putExtra("source_name",b.sourceName);x.putExtra("source_url",b.sourceUrl);x.putExtra("source_json",b.sourceJson);startActivity(x);});return c;}
 private TextView pageButton(String s){TextView v=tx(s,14,green,true);v.setGravity(Gravity.CENTER);return v;}private TextView tx(String s,int z,int color,boolean bold){TextView v=new TextView(this);v.setText(s);v.setTextSize(z);v.setTextColor(color);v.setTypeface(Typeface.create("sans",bold?Typeface.BOLD:Typeface.NORMAL));return v;}private LinearLayout.LayoutParams mp(int l,int t,int r,int b){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(dp(l),dp(t),dp(r),dp(b));return p;}private int dp(float n){return(int)(n*getResources().getDisplayMetrics().density+.5f);}
}
