package com.xiaoxiaoshuo.reader;
import android.content.Context;import android.content.SharedPreferences;import android.database.Cursor;import android.database.sqlite.SQLiteDatabase;import org.json.*;import java.io.File;import java.util.*;
public final class LegacySourceStore{
 public static final class SourceInfo{public String url="",name="",group="",json="";public boolean enabled,compatible;public int healthState,failures,score;public long latency,checkedAt,successAt;}
 public static final class BookInfo{public String title="",author="",intro="",cover="",content="";}
 public static final class State{public final ArrayList<SourceInfo> all=new ArrayList<>(),selected=new ArrayList<>();public boolean legacyDatabaseFound;public String message="";}
 private LegacySourceStore(){}
 public static State prepare(Context context,int limit){State out=new State();LinkedHashMap<String,SourceInfo> merged=new LinkedHashMap<>();Set<String> blocked=blacklistSet(context);File dbFile=context.getDatabasePath("xiaoxiaoshuo.db");if(dbFile.exists()){out.legacyDatabaseFound=true;SQLiteDatabase db=null;Cursor c=null;try{db=SQLiteDatabase.openDatabase(dbFile.getAbsolutePath(),null,SQLiteDatabase.OPEN_READONLY);if(tableExists(db,"sources")){c=db.rawQuery("SELECT * FROM sources",null);while(c.moveToNext()){SourceInfo s=new SourceInfo();s.url=str(c,"source_url");s.name=str(c,"name");s.group=str(c,"source_group");s.json=str(c,"json");s.enabled=num(c,"enabled",1)==1;s.compatible=num(c,"compatible",0)==1;s.healthState=num(c,"health_state",0);s.latency=longNum(c,"health_latency",0);s.failures=num(c,"health_failures",0);s.checkedAt=longNum(c,"health_checked_at",0);s.successAt=longNum(c,"health_success_at",0);applyHealthOverride(context,s);s.score=score(s);if(valid(s)&&!blocked.contains(s.url))merged.put(s.url,s);}}}catch(Throwable e){out.message="旧书源读取失败："+e.getClass().getSimpleName();}finally{if(c!=null)c.close();if(db!=null)db.close();}}
  mergePrefs(context,"manual_sources",merged,blocked,6000);mergePrefs(context,"auto_sources",merged,blocked,8500);out.all.addAll(merged.values());ArrayList<SourceInfo> candidates=new ArrayList<>();for(SourceInfo s:out.all)if(s.enabled)candidates.add(s);Collections.sort(candidates,(a,b)->{int x=Integer.compare(b.score,a.score);if(x!=0)return x;int l=Long.compare(normalLatency(a.latency),normalLatency(b.latency));if(l!=0)return l;return a.name.compareToIgnoreCase(b.name);});int cap=limit<=0?candidates.size():Math.min(limit,candidates.size());for(int i=0;i<cap;i++)out.selected.add(candidates.get(i));persistSelection(context,out.selected);if(out.message.length()==0)out.message="恢复 "+out.all.size()+" 个外部书源 · 智能启用 "+out.selected.size()+" 个";return out;}
 private static void mergePrefs(Context c,String pref,LinkedHashMap<String,SourceInfo> merged,Set<String> blocked,int bonus){Set<String> raws=c.getSharedPreferences(pref,Context.MODE_PRIVATE).getStringSet("jsons",Collections.emptySet());for(String json:raws){try{SourceInfo s=fromJson(json);applyHealthOverride(c,s);s.score=score(s)+bonus;if(valid(s)&&!blocked.contains(s.url))merged.put(s.url,s);}catch(Throwable ignored){}}}
 public static int addManualSources(Context c,String raw)throws Exception{return mergeJsonIntoPref(c,"manual_sources",raw,false);}
 public static int replaceAutoSources(Context c,List<String> jsons){try{JSONArray a=new JSONArray();for(String s:jsons){try{a.put(new JSONObject(s));}catch(Throwable ignored){}}return mergeJsonIntoPref(c,"auto_sources",a.toString(),true);}catch(Throwable e){return 0;}}
 private static int mergeJsonIntoPref(Context c,String pref,String raw,boolean auto)throws Exception{if(raw==null||raw.trim().length()==0)return 0;ArrayList<JSONObject> objs=new ArrayList<>();Object root=new JSONTokener(raw.trim()).nextValue();if(root instanceof JSONArray){JSONArray a=(JSONArray)root;for(int i=0;i<a.length();i++){JSONObject o=a.optJSONObject(i);if(o!=null)objs.add(o);}}else if(root instanceof JSONObject)objs.add((JSONObject)root);SharedPreferences p=c.getSharedPreferences(pref,Context.MODE_PRIVATE);LinkedHashSet<String> set=new LinkedHashSet<>(p.getStringSet("jsons",Collections.emptySet()));LinkedHashMap<String,String> byUrl=new LinkedHashMap<>();for(String old:set){try{JSONObject o=new JSONObject(old);String u=o.optString("bookSourceUrl","").trim();if(u.length()>0)byUrl.put(u,old);}catch(Throwable ignored){}}int added=0;for(JSONObject o:objs){String u=o.optString("bookSourceUrl","").trim();if(!u.startsWith("http"))continue;o.put("enabled",true);if(auto&&!o.has("bookSourceGroup"))o.put("bookSourceGroup","源仓库自动更新");if(!byUrl.containsKey(u))added++;byUrl.put(u,o.toString());}p.edit().putStringSet("jsons",new LinkedHashSet<>(byUrl.values())).apply();return added;}
 public static void recordHealth(Context c,String url,boolean ok,long latency){if(url==null||url.length()==0)return;SharedPreferences p=c.getSharedPreferences("source_health_runtime",Context.MODE_PRIVATE);String k=key(url);int fail=p.getInt("f_"+k,0);SharedPreferences.Editor e=p.edit().putLong("l_"+k,latency).putLong("c_"+k,System.currentTimeMillis());if(ok)e.putInt("f_"+k,0).putInt("s_"+k,1).putLong("ok_"+k,System.currentTimeMillis());else e.putInt("f_"+k,fail+1).putInt("s_"+k,-1);e.apply();}
 public static int failureCount(Context c,String url){return c.getSharedPreferences("source_health_runtime",Context.MODE_PRIVATE).getInt("f_"+key(url),0);}
 public static void blacklist(Context c,String url){if(url==null||url.length()==0)return;SharedPreferences p=c.getSharedPreferences("source_blacklist",Context.MODE_PRIVATE);LinkedHashSet<String> s=new LinkedHashSet<>(p.getStringSet("urls",Collections.emptySet()));s.add(url);p.edit().putStringSet("urls",s).apply();}
 public static boolean removeNonLegacySource(Context c,String url){boolean removed=false;removed|=removeFromPref(c,"manual_sources",url);removed|=removeFromPref(c,"auto_sources",url);if(removed)blacklist(c,url);return removed;}
 private static boolean removeFromPref(Context c,String pref,String url){SharedPreferences p=c.getSharedPreferences(pref,Context.MODE_PRIVATE);Set<String> old=p.getStringSet("jsons",Collections.emptySet());LinkedHashSet<String> keep=new LinkedHashSet<>();boolean removed=false;for(String raw:old){try{JSONObject o=new JSONObject(raw);if(url.equals(o.optString("bookSourceUrl","").trim())){removed=true;continue;}}catch(Throwable ignored){}keep.add(raw);}if(removed)p.edit().putStringSet("jsons",keep).apply();return removed;}
 private static Set<String> blacklistSet(Context c){return new LinkedHashSet<>(c.getSharedPreferences("source_blacklist",Context.MODE_PRIVATE).getStringSet("urls",Collections.emptySet()));}
 private static void applyHealthOverride(Context c,SourceInfo s){SharedPreferences p=c.getSharedPreferences("source_health_runtime",Context.MODE_PRIVATE);String k=key(s.url);if(p.contains("f_"+k))s.failures=p.getInt("f_"+k,s.failures);if(p.contains("s_"+k))s.healthState=p.getInt("s_"+k,s.healthState);if(p.contains("l_"+k))s.latency=p.getLong("l_"+k,s.latency);if(p.contains("c_"+k))s.checkedAt=p.getLong("c_"+k,s.checkedAt);if(p.contains("ok_"+k))s.successAt=p.getLong("ok_"+k,s.successAt);}
 public static ArrayList<BookInfo> loadLegacyBooks(Context context,int limit){ArrayList<BookInfo> list=new ArrayList<>();File f=context.getDatabasePath("xiaoxiaoshuo.db");if(!f.exists())return list;SQLiteDatabase db=null;Cursor c=null;try{db=SQLiteDatabase.openDatabase(f.getAbsolutePath(),null,SQLiteDatabase.OPEN_READONLY);if(!tableExists(db,"books"))return list;c=db.rawQuery("SELECT * FROM books ORDER BY last_read_at DESC, updated_at DESC LIMIT "+Math.max(1,limit),null);while(c.moveToNext()){BookInfo b=new BookInfo();b.title=str(c,"title");b.author=str(c,"author");b.intro=AiTypesetter.compactIntro(str(c,"intro"));b.cover=str(c,"cover_url");b.content=str(c,"content");if(b.title.length()>0)list.add(b);}}catch(Throwable ignored){}finally{if(c!=null)c.close();if(db!=null)db.close();}return list;}
 private static SourceInfo fromJson(String json)throws Exception{JSONObject o=new JSONObject(json);SourceInfo s=new SourceInfo();s.url=o.optString("bookSourceUrl","").trim();s.name=o.optString("bookSourceName","未命名书源");s.group=o.optString("bookSourceGroup","手动添加");s.json=o.toString();s.enabled=o.optBoolean("enabled",true);s.compatible=s.url.startsWith("http");s.healthState=0;s.score=score(s);return s;}private static boolean valid(SourceInfo s){return s!=null&&s.url!=null&&(s.url.startsWith("http://")||s.url.startsWith("https://"))&&s.json!=null&&s.json.trim().startsWith("{");}
 private static void persistSelection(Context c,List<SourceInfo> selected){LinkedHashSet<String> urls=new LinkedHashSet<>();for(SourceInfo s:selected)urls.add(s.url);c.getSharedPreferences("source_selection",Context.MODE_PRIVATE).edit().putStringSet("smart_80_urls",urls).putInt("smart_80_count",urls.size()).putLong("smart_80_updated",System.currentTimeMillis()).apply();}private static int score(SourceInfo s){int v=0;if(s.compatible)v+=50000;if(s.healthState==1)v+=45000;else if(s.healthState==0)v+=8000;else v-=25000;if(s.enabled)v+=15000;if(s.successAt>0)v+=12000;v-=Math.min(30000,s.failures*5000);if(s.latency>0){if(s.latency<800)v+=12000;else if(s.latency<1500)v+=9000;else if(s.latency<3000)v+=5000;else v-=3000;}if(s.url!=null&&s.url.toLowerCase(Locale.ROOT).startsWith("https://"))v+=2500;if(s.json!=null&&s.json.length()>100)v+=1500;return v;}private static long normalLatency(long l){return l<=0?Long.MAX_VALUE/4:l;}private static boolean tableExists(SQLiteDatabase db,String table){Cursor c=null;try{c=db.rawQuery("SELECT name FROM sqlite_master WHERE type='table' AND name=?",new String[]{table});return c.moveToFirst();}catch(Throwable e){return false;}finally{if(c!=null)c.close();}}private static String str(Cursor c,String n){int i=c.getColumnIndex(n);if(i<0||c.isNull(i))return "";String s=c.getString(i);return s==null?"":s;}private static int num(Cursor c,String n,int d){int i=c.getColumnIndex(n);return i<0||c.isNull(i)?d:c.getInt(i);}private static long longNum(Cursor c,String n,long d){int i=c.getColumnIndex(n);return i<0||c.isNull(i)?d:c.getLong(i);}private static String key(String s){return Integer.toHexString((s==null?"":s).hashCode());}
}
