package com.xiaoxiaoshuo.reader;
import android.content.Context;import dalvik.system.DexClassLoader;import java.io.*;import java.lang.reflect.*;import java.util.*;
public final class LegacyDexBridge{
 public static final class BookResult{public String title="",author="",intro="",coverUrl="",bookUrl="",sourceName="",sourceUrl="",sourceJson="";}
 public static final class Chapter{public String name="",url="";public Chapter(String n,String u){name=n==null?"":n;url=u==null?"":u;}}
 private static volatile LegacyDexBridge instance;private final ClassLoader loader;private final Class<?> bookSourceCls,sourceEngineCls,netBookCls,chapterCls;private final Method fromJson,search,loadDetail,loadChapters,loadContent;private final Constructor<?> netBookCtor,chapterCtor;
 public static LegacyDexBridge get(Context c)throws Exception{LegacyDexBridge x=instance;if(x==null){synchronized(LegacyDexBridge.class){x=instance;if(x==null)instance=x=new LegacyDexBridge(c.getApplicationContext());}}return x;}
 private LegacyDexBridge(Context c)throws Exception{File dex=installDex(c);loader=new DexClassLoader(dex.getAbsolutePath(),c.getCodeCacheDir().getAbsolutePath(),null,c.getClassLoader());bookSourceCls=loader.loadClass("com.xiaoxiaoshuo.reader.BookSource");sourceEngineCls=loader.loadClass("com.xiaoxiaoshuo.reader.SourceEngine");netBookCls=loader.loadClass("com.xiaoxiaoshuo.reader.NetBook");chapterCls=loader.loadClass("com.xiaoxiaoshuo.reader.ChapterRef");fromJson=bookSourceCls.getMethod("fromJson",String.class);search=sourceEngineCls.getMethod("search",bookSourceCls,String.class,int.class);loadDetail=sourceEngineCls.getMethod("loadDetail",bookSourceCls,netBookCls);loadChapters=sourceEngineCls.getMethod("loadChapters",bookSourceCls,netBookCls);loadContent=sourceEngineCls.getMethod("loadContent",bookSourceCls,chapterCls);netBookCtor=netBookCls.getConstructor();chapterCtor=chapterCls.getConstructor(String.class,String.class);}
 private static File installDex(Context c)throws IOException{File out=new File(c.getCodeCacheDir(),"legacy_source_engine_v946.dex");if(out.isFile()&&out.length()>500000)return out;File tmp=new File(c.getCodeCacheDir(),"legacy_source_engine_v946.tmp");InputStream in=c.getAssets().open("legacy-engine.dex");FileOutputStream os=new FileOutputStream(tmp);byte[] buf=new byte[32768];int n;while((n=in.read(buf))>0)os.write(buf,0,n);os.flush();os.getFD().sync();os.close();in.close();if(out.exists())out.delete();if(!tmp.renameTo(out)){FileInputStream a=new FileInputStream(tmp);FileOutputStream b=new FileOutputStream(out);while((n=a.read(buf))>0)b.write(buf,0,n);b.close();a.close();tmp.delete();}out.setReadable(true,true);out.setWritable(false,true);out.setExecutable(false,false);return out;}
 public List<BookResult> search(LegacySourceStore.SourceInfo src,String keyword,int page)throws Exception{if(src==null||src.json==null||src.json.trim().length()<2)return Collections.emptyList();Object source=fromJson.invoke(null,src.json);Object raw=search.invoke(null,source,keyword,Math.max(1,page));if(!(raw instanceof List))return Collections.emptyList();ArrayList<BookResult> out=new ArrayList<>();for(Object item:(List<?>)raw){if(item==null)continue;BookResult b=readBook(item,src);if(b.title.length()>0)out.add(b);}return out;}
 public BookResult loadDetail(BookResult b)throws Exception{if(b==null||b.sourceJson.length()==0)return b;Object source=fromJson.invoke(null,b.sourceJson),net=makeNetBook(b);Object d=loadDetail.invoke(null,source,net);if(d==null)d=net;BookResult r=readBook(d,sourceInfo(b));r.sourceJson=b.sourceJson;return r;}
 public List<Chapter> loadCatalog(BookResult b)throws Exception{if(b==null||b.sourceJson.length()==0)return Collections.emptyList();Object source=fromJson.invoke(null,b.sourceJson),net=makeNetBook(b);try{Object d=loadDetail.invoke(null,source,net);if(d!=null)net=d;}catch(Throwable ignored){}Object raw=loadChapters.invoke(null,source,net);if(!(raw instanceof List))return Collections.emptyList();ArrayList<Chapter> out=new ArrayList<>();for(Object ch:(List<?>)raw){if(ch==null)continue;String n=field(ch,"name"),u=field(ch,"url");if(n.length()>0&&u.length()>0)out.add(new Chapter(n,u));}return out;}
 public String loadChapter(String sourceJson,String name,String url)throws Exception{Object source=fromJson.invoke(null,sourceJson),ch=chapterCtor.newInstance(name,url);Object text=loadContent.invoke(null,source,ch);return text==null?"":String.valueOf(text);}
 private Object makeNetBook(BookResult b)throws Exception{Object n=netBookCtor.newInstance();set(n,"name",b.title);set(n,"author",b.author);set(n,"intro",b.intro);set(n,"coverUrl",b.coverUrl);set(n,"bookUrl",b.bookUrl);set(n,"sourceName",b.sourceName);set(n,"sourceUrl",b.sourceUrl);return n;}
 private BookResult readBook(Object n,LegacySourceStore.SourceInfo src){BookResult b=new BookResult();b.title=field(n,"name");b.author=field(n,"author");b.intro=AiTypesetter.compactIntro(field(n,"intro"));b.coverUrl=field(n,"coverUrl");b.bookUrl=field(n,"bookUrl");b.sourceName=field(n,"sourceName");b.sourceUrl=field(n,"sourceUrl");if(src!=null){if(b.sourceName.length()==0)b.sourceName=src.name;if(b.sourceUrl.length()==0)b.sourceUrl=src.url;b.sourceJson=src.json;}return b;}
 private LegacySourceStore.SourceInfo sourceInfo(BookResult b){LegacySourceStore.SourceInfo s=new LegacySourceStore.SourceInfo();s.name=b.sourceName;s.url=b.sourceUrl;s.json=b.sourceJson;s.enabled=true;return s;}private static String field(Object o,String n){try{Field f=o.getClass().getField(n);Object v=f.get(o);return v==null?"":String.valueOf(v);}catch(Throwable e){return "";}}private static void set(Object o,String n,String v){try{o.getClass().getField(n).set(o,v==null?"":v);}catch(Throwable ignored){}}
}