package com.xiaoxiaoshuo.reader;
import android.app.*;import android.os.*;import android.content.*;import android.graphics.*;import android.graphics.drawable.GradientDrawable;import android.view.*;import android.widget.*;import java.io.*;import java.net.*;import java.util.*;
public class SourceManagerActivity extends Activity{
 private final int green=Color.rgb(49,88,71);private LinearLayout list;private TextView status;
 @Override public void onCreate(Bundle b){super.onCreate(b);build();refresh();}
 private void build(){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(Color.rgb(247,244,238));root.setPadding(dp(16),dp(10),dp(16),0);LinearLayout top=new LinearLayout(this);top.setGravity(Gravity.CENTER_VERTICAL);TextView back=tx("‹",32,green,true);back.setGravity(Gravity.CENTER);back.setOnClickListener(v->finish());top.addView(back,new LinearLayout.LayoutParams(dp(44),dp(50)));top.addView(tx("书源管理",22,Color.rgb(43,55,49),true),new LinearLayout.LayoutParams(0,dp(50),1));TextView add=tx("＋ 添加",15,green,true);add.setGravity(Gravity.CENTER);add.setOnClickListener(v->showAdd());top.addView(add,new LinearLayout.LayoutParams(dp(76),dp(50)));root.addView(top);status=tx("",13,Color.rgb(118,111,101),false);status.setPadding(dp(4),dp(10),dp(4),dp(12));root.addView(status);ScrollView sv=new ScrollView(this);list=new LinearLayout(this);list.setOrientation(LinearLayout.VERTICAL);list.setPadding(0,0,0,dp(40));sv.addView(list);root.addView(sv,new LinearLayout.LayoutParams(-1,0,1));setContentView(root);getWindow().setStatusBarColor(Color.rgb(247,244,238));getWindow().getDecorView().setSystemUiVisibility(View.SYSTEM_UI_FLAG_LIGHT_STATUS_BAR);}
 private void refresh(){LegacySourceStore.State st=LegacySourceStore.prepare(this,80);status.setText("外部书源 "+st.all.size()+" 个 · 智能启用 "+st.selected.size()+" 个 · 默认检索池80");list.removeAllViews();TextView hint=tx("优先展示智能评分最高的书源。评分综合兼容状态、成功率、延迟和失败次数；未入选的书源不会被删除。",13,Color.rgb(105,99,91),false);hint.setPadding(dp(12),dp(12),dp(12),dp(16));list.addView(hint);int n=0;for(LegacySourceStore.SourceInfo s:st.selected){LinearLayout row=card();LinearLayout info=new LinearLayout(this);info.setOrientation(LinearLayout.VERTICAL);info.addView(tx((++n)+" · "+s.name,15,Color.rgb(47,57,52),true));TextView sub=tx((s.group.length()>0?s.group+" · ":"")+"评分 "+s.score+(s.latency>0?" · "+s.latency+"ms":""),12,Color.rgb(127,119,108),false);sub.setPadding(0,dp(4),0,0);info.addView(sub);row.addView(info,new LinearLayout.LayoutParams(0,-2,1));TextView ok=tx("已启用",12,green,true);ok.setGravity(Gravity.CENTER);row.addView(ok,new LinearLayout.LayoutParams(dp(58),dp(46)));list.addView(row,mp(0,0,0,8));}}
 private void showAdd(){final EditText e=new EditText(this);e.setHint("粘贴书源 JSON / JSON 数组，或输入书源订阅网址");e.setMinLines(5);e.setGravity(Gravity.TOP);e.setPadding(dp(12),dp(12),dp(12),dp(12));new AlertDialog.Builder(this).setTitle("添加更多书源").setView(e).setNegativeButton("取消",null).setPositiveButton("导入",(d,w)->importText(e.getText().toString().trim())).show();}
 private void importText(String raw){if(raw.length()==0)return;if(raw.startsWith("http://")||raw.startsWith("https://")){status.setText("正在从网址获取书源…");new Thread(()->{try{HttpURLConnection h=(HttpURLConnection)new URL(raw).openConnection();h.setConnectTimeout(8000);h.setReadTimeout(12000);h.setRequestProperty("User-Agent","XiaoXiaoShuo/10.0");InputStream in=h.getInputStream();ByteArrayOutputStream out=new ByteArrayOutputStream();byte[] b=new byte[16384];int n,total=0;while((n=in.read(b))>0&&total<4*1024*1024){out.write(b,0,n);total+=n;}in.close();int count=LegacySourceStore.addManualSources(this,new String(out.toByteArray(),"UTF-8"));runOnUiThread(()->{Toast.makeText(this,"导入 "+count+" 个新书源",Toast.LENGTH_SHORT).show();refresh();});}catch(Throwable ex){runOnUiThread(()->Toast.makeText(this,"导入失败：请检查网址或书源格式",Toast.LENGTH_LONG).show());}}).start();}else{try{int count=LegacySourceStore.addManualSources(this,raw);Toast.makeText(this,"导入 "+count+" 个新书源",Toast.LENGTH_SHORT).show();refresh();}catch(Throwable e){Toast.makeText(this,"JSON格式无法识别",Toast.LENGTH_LONG).show();}}}
 private LinearLayout card(){LinearLayout c=new LinearLayout(this);c.setGravity(Gravity.CENTER_VERTICAL);c.setPadding(dp(14),dp(11),dp(14),dp(11));GradientDrawable g=new GradientDrawable();g.setColor(Color.WHITE);g.setCornerRadius(dp(15));c.setBackground(g);return c;}private TextView tx(String s,int z,int c,boolean b){TextView v=new TextView(this);v.setText(s);v.setTextSize(z);v.setTextColor(c);v.setTypeface(Typeface.create("sans",b?Typeface.BOLD:Typeface.NORMAL));return v;}private LinearLayout.LayoutParams mp(int l,int t,int r,int b){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(dp(l),dp(t),dp(r),dp(b));return p;}private int dp(float n){return(int)(n*getResources().getDisplayMetrics().density+.5f);}
}